import { useState } from "react";
import { loadProfile, saveProfile } from "../lib/storage";
import type { StudentProfile } from "../lib/types";
const empty: StudentProfile = { nickname: "乖乖", grade: 1, semester: "上", textbook: { chinese: "人教版", math: "人教版", english: "人教版" }, dailyTimeSlot: "每天下午约45分钟", weakSubjects: [], enableEnglish: true, enableQuality: true, updatedAt: new Date().toISOString() };
export default function ProfilePage(){
  const [p,setP]=useState<StudentProfile>(loadProfile() ?? empty);
  const [msg,setMsg]=useState("");
  function save(){ if(!p.nickname.trim()) return setMsg("请填写昵称"); const next={...p, updatedAt:new Date().toISOString()}; saveProfile(next); setMsg("已保存，返回今日查看新计划"); }
  return (<div className="page"><h2>档案 / 设置</h2><div className="form"><label>昵称<input value={p.nickname} onChange={e=>setP({...p, nickname:e.target.value})} /></label><label>年级<select value={p.grade} onChange={e=>setP({...p, grade: Number(e.target.value) as any})}><option value={1}>一年级</option><option value={2}>二年级</option><option value={3}>三年级</option><option value={4}>四年级</option><option value={5}>五年级</option><option value={6}>六年级</option></select></label><label>学期<select value={p.semester} onChange={e=>setP({...p, semester:e.target.value as any})}><option value="上">上</option><option value="下">下</option></select></label><label>语文教材<select value={p.textbook.chinese} onChange={e=>setP({...p, textbook:{...p.textbook, chinese:e.target.value as any}})}><option>人教版</option><option>北师大版</option><option>苏教版</option><option>其他</option></select></label><label>数学教材<select value={p.textbook.math} onChange={e=>setP({...p, textbook:{...p.textbook, math:e.target.value as any}})}><option>人教版</option><option>北师大版</option><option>苏教版</option><option>其他</option></select></label><label>英语教材<select value={p.textbook.english} onChange={e=>setP({...p, textbook:{...p.textbook, english:e.target.value as any}})}><option>人教版</option><option>北师大版</option><option>苏教版</option><option>其他</option></select></label><label>每日时段<input value={p.dailyTimeSlot} onChange={e=>setP({...p, dailyTimeSlot:e.target.value})} /></label><label className="check"><input type="checkbox" checked={p.enableEnglish} onChange={e=>setP({...p, enableEnglish:e.target.checked})} />启用英语模块</label><label className="check"><input type="checkbox" checked={p.enableQuality} onChange={e=>setP({...p, enableQuality:e.target.checked})} />启用素质与劳动</label><button onClick={save}>保存</button>{msg && <span className="muted">{msg}</span>}</div><p className="muted">修改年级/学期后，次日计划按新年级生成，旧记录可在“我的-归档”回看。</p></div>);
}
